# coding:utf-8

from api.mall_center_sys._mgmt_sys_getProvinceList import _mgmt_sys_getProvinceList
from setting import P1, P2, P3

import os
import allure


@allure.feature("mall_mgmt_application")
class TestClass:
    """
    获取省份信息
    /mgmt/sys/getProvinceList
    """
    def setup_class(self):
        self.access_token = os.environ["access_token"]
           
    @allure.story("/mgmt/sys/getProvinceList")
    @allure.severity(P2)
    @allure.title("获取省份信息-成功路径: 新建服务中心时获取信息检查")
    def test_mgmt_sys_getProvinceList(self):
        
        with _mgmt_sys_getProvinceList(self.access_token) as r:
            assert r.status_code == 200
            assert r.json()["code"] == 200
            assert r.json()["data"] == [
                {
                    "id": None,
                    "code": "110000000000",
                    "provinceId": "110000000000",
                    "provinceName": "北京市",
                    "provinceCode": "110000000000",
                    "cityName": None,
                    "cityCode": None,
                    "cityId": None,
                    "districtName": None,
                    "districtCode": None,
                    "districtId": None,
                    "streetName": None,
                    "streetId": None,
                    "streetCode": None,
                    "affiliatedCount": None}, 
                {
                    "id": None,
                    "code": "120000000000",
                    "provinceId": "120000000000",
                    "provinceName": "天津市",
                    "provinceCode": "120000000000",
                    "cityName": None,
                    "cityCode": None,
                    "cityId": None,
                    "districtName": None,
                    "districtCode": None,
                    "districtId": None,
                    "streetName": None,
                    "streetId": None,
                    "streetCode": None,
                    "affiliatedCount": None},
                {
                    "id": None,
                    "code": "130000000000",
                    "provinceId": "130000000000",
                    "provinceName": "河北省",
                    "provinceCode": "130000000000",
                    "cityName": None,
                    "cityCode": None,
                    "cityId": None,
                    "districtName": None,
                    "districtCode": None,
                    "districtId": None,
                    "streetName": None,
                    "streetId": None,
                    "streetCode": None,
                    "affiliatedCount": None}, 
                {
                "id": None,
                "code": "140000000000",
                "provinceId": "140000000000",
                "provinceName": "山西省",
                "provinceCode": "140000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "150000000000",
                "provinceId": "150000000000",
                "provinceName": "内蒙古自治区",
                "provinceCode": "150000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "210000000000",
                "provinceId": "210000000000",
                "provinceName": "辽宁省",
                "provinceCode": "210000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "220000000000",
                "provinceId": "220000000000",
                "provinceName": "吉林省",
                "provinceCode": "220000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "230000000000",
                "provinceId": "230000000000",
                "provinceName": "黑龙江省",
                "provinceCode": "230000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "310000000000",
                "provinceId": "310000000000",
                "provinceName": "上海市",
                "provinceCode": "310000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "320000000000",
                "provinceId": "320000000000",
                "provinceName": "江苏省",
                "provinceCode": "320000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "330000000000",
                "provinceId": "330000000000",
                "provinceName": "浙江省",
                "provinceCode": "330000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "340000000000",
                "provinceId": "340000000000",
                "provinceName": "安徽省",
                "provinceCode": "340000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "350000000000",
                "provinceId": "350000000000",
                "provinceName": "福建省",
                "provinceCode": "350000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "360000000000",
                "provinceId": "360000000000",
                "provinceName": "江西省",
                "provinceCode": "360000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "370000000000",
                "provinceId": "370000000000",
                "provinceName": "山东省",
                "provinceCode": "370000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "410000000000",
                "provinceId": "410000000000",
                "provinceName": "河南省",
                "provinceCode": "410000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "420000000000",
                "provinceId": "420000000000",
                "provinceName": "湖北省",
                "provinceCode": "420000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "430000000000",
                "provinceId": "430000000000",
                "provinceName": "湖南省",
                "provinceCode": "430000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "440000000000",
                "provinceId": "440000000000",
                "provinceName": "广东省",
                "provinceCode": "440000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "450000000000",
                "provinceId": "450000000000",
                "provinceName": "广西壮族自治区",
                "provinceCode": "450000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "460000000000",
                "provinceId": "460000000000",
                "provinceName": "海南省",
                "provinceCode": "460000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "500000000000",
                "provinceId": "500000000000",
                "provinceName": "重庆市",
                "provinceCode": "500000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "510000000000",
                "provinceId": "510000000000",
                "provinceName": "四川省",
                "provinceCode": "510000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "520000000000",
                "provinceId": "520000000000",
                "provinceName": "贵州省",
                "provinceCode": "520000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "530000000000",
                "provinceId": "530000000000",
                "provinceName": "云南省",
                "provinceCode": "530000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "540000000000",
                "provinceId": "540000000000",
                "provinceName": "西藏自治区",
                "provinceCode": "540000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "610000000000",
                "provinceId": "610000000000",
                "provinceName": "陕西省",
                "provinceCode": "610000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "620000000000",
                "provinceId": "620000000000",
                "provinceName": "甘肃省",
                "provinceCode": "620000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            },
                {
                "id": None,
                "code": "630000000000",
                "provinceId": "630000000000",
                "provinceName": "青海省",
                "provinceCode": "630000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "640000000000",
                "provinceId": "640000000000",
                "provinceName": "宁夏回族自治区",
                "provinceCode": "640000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }, 
                {
                "id": None,
                "code": "650000000000",
                "provinceId": "650000000000",
                "provinceName": "新疆维吾尔自治区",
                "provinceCode": "650000000000",
                "cityName": None,
                "cityCode": None,
                "cityId": None,
                "districtName": None,
                "districtCode": None,
                "districtId": None,
                "streetName": None,
                "streetId": None,
                "streetCode": None,
                "affiliatedCount": None
            }
            ]
